# Generated by Django 5.1.6 on 2025-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill Name', max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='skills',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills',
            field=models.ManyToManyField(to='portfolio.skills'),
        ),
    ]
