# Generated by Django 5.1.6 on 2025-03-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skills_delete_skill_remove_aboutme_skills_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
