# Generated by Django 5.1.7 on 2025-03-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(help_text='Education End date', max_length=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(help_text='Education Start date', max_length=4),
        ),
        migrations.AlterField(
            model_name='experience',
            name='about_me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(help_text='Experience End date', max_length=4),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.CharField(help_text='Experience Start date', max_length=4),
        ),
    ]
