# Generated by Django 5.1.7 on 2025-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_education_end_year_alter_education_start_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Enter your skill name', max_length=100, unique=True),
        ),
    ]
